/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as StartRouteImport } from './routes/start'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppNumbersRouteImport } from './routes/_authenticated/app.numbers'
import { Route as AuthenticatedAppNewJobRouteImport } from './routes/_authenticated/app.new-job'
import { Route as AuthenticatedAppListsRouteImport } from './routes/_authenticated/app.lists'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/app.dashboard'
import { Route as AuthenticatedAppComplianceRouteImport } from './routes/_authenticated/app.compliance'
import { Route as AuthenticatedAppCampaignsRouteImport } from './routes/_authenticated/app.campaigns'
import { Route as AuthenticatedAppBillingRouteImport } from './routes/_authenticated/app.billing'
import { Route as AuthenticatedAppNewJobUploadRouteImport } from './routes/_authenticated/app.new-job.upload'
import { Route as AuthenticatedAppNewJobRecordsRouteImport } from './routes/_authenticated/app.new-job.records'
import { Route as AuthenticatedAppNewJobBusinessRouteImport } from './routes/_authenticated/app.new-job.business'
import { Route as AuthenticatedAppJobsJobIdRouteImport } from './routes/_authenticated/app.jobs.$jobId'
import { Route as AuthenticatedAppCampaignsCampaignIdRouteImport } from './routes/_authenticated/app.campaigns.$campaignId'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppNumbersRoute = AuthenticatedAppNumbersRouteImport.update({
  id: '/numbers',
  path: '/numbers',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppNewJobRoute = AuthenticatedAppNewJobRouteImport.update({
  id: '/new-job',
  path: '/new-job',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppListsRoute = AuthenticatedAppListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppComplianceRoute =
  AuthenticatedAppComplianceRouteImport.update({
    id: '/compliance',
    path: '/compliance',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCampaignsRoute =
  AuthenticatedAppCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBillingRoute = AuthenticatedAppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppNewJobUploadRoute =
  AuthenticatedAppNewJobUploadRouteImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => AuthenticatedAppNewJobRoute,
  } as any)
const AuthenticatedAppNewJobRecordsRoute =
  AuthenticatedAppNewJobRecordsRouteImport.update({
    id: '/records',
    path: '/records',
    getParentRoute: () => AuthenticatedAppNewJobRoute,
  } as any)
const AuthenticatedAppNewJobBusinessRoute =
  AuthenticatedAppNewJobBusinessRouteImport.update({
    id: '/business',
    path: '/business',
    getParentRoute: () => AuthenticatedAppNewJobRoute,
  } as any)
const AuthenticatedAppJobsJobIdRoute =
  AuthenticatedAppJobsJobIdRouteImport.update({
    id: '/jobs/$jobId',
    path: '/jobs/$jobId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCampaignsCampaignIdRoute =
  AuthenticatedAppCampaignsCampaignIdRouteImport.update({
    id: '/$campaignId',
    path: '/$campaignId',
    getParentRoute: () => AuthenticatedAppCampaignsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compliance': typeof ComplianceRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/industries': typeof IndustriesRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/sign-in': typeof SignInRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start': typeof StartRoute
  '/templates': typeof TemplatesRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/campaigns': typeof AuthenticatedAppCampaignsRouteWithChildren
  '/app/compliance': typeof AuthenticatedAppComplianceRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/lists': typeof AuthenticatedAppListsRoute
  '/app/new-job': typeof AuthenticatedAppNewJobRouteWithChildren
  '/app/numbers': typeof AuthenticatedAppNumbersRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/campaigns/$campaignId': typeof AuthenticatedAppCampaignsCampaignIdRoute
  '/app/jobs/$jobId': typeof AuthenticatedAppJobsJobIdRoute
  '/app/new-job/business': typeof AuthenticatedAppNewJobBusinessRoute
  '/app/new-job/records': typeof AuthenticatedAppNewJobRecordsRoute
  '/app/new-job/upload': typeof AuthenticatedAppNewJobUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compliance': typeof ComplianceRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/industries': typeof IndustriesRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/sign-in': typeof SignInRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start': typeof StartRoute
  '/templates': typeof TemplatesRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/campaigns': typeof AuthenticatedAppCampaignsRouteWithChildren
  '/app/compliance': typeof AuthenticatedAppComplianceRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/lists': typeof AuthenticatedAppListsRoute
  '/app/new-job': typeof AuthenticatedAppNewJobRouteWithChildren
  '/app/numbers': typeof AuthenticatedAppNumbersRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/campaigns/$campaignId': typeof AuthenticatedAppCampaignsCampaignIdRoute
  '/app/jobs/$jobId': typeof AuthenticatedAppJobsJobIdRoute
  '/app/new-job/business': typeof AuthenticatedAppNewJobBusinessRoute
  '/app/new-job/records': typeof AuthenticatedAppNewJobRecordsRoute
  '/app/new-job/upload': typeof AuthenticatedAppNewJobUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/compliance': typeof ComplianceRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/industries': typeof IndustriesRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/sign-in': typeof SignInRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start': typeof StartRoute
  '/templates': typeof TemplatesRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/billing': typeof AuthenticatedAppBillingRoute
  '/_authenticated/app/campaigns': typeof AuthenticatedAppCampaignsRouteWithChildren
  '/_authenticated/app/compliance': typeof AuthenticatedAppComplianceRoute
  '/_authenticated/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/app/lists': typeof AuthenticatedAppListsRoute
  '/_authenticated/app/new-job': typeof AuthenticatedAppNewJobRouteWithChildren
  '/_authenticated/app/numbers': typeof AuthenticatedAppNumbersRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/campaigns/$campaignId': typeof AuthenticatedAppCampaignsCampaignIdRoute
  '/_authenticated/app/jobs/$jobId': typeof AuthenticatedAppJobsJobIdRoute
  '/_authenticated/app/new-job/business': typeof AuthenticatedAppNewJobBusinessRoute
  '/_authenticated/app/new-job/records': typeof AuthenticatedAppNewJobRecordsRoute
  '/_authenticated/app/new-job/upload': typeof AuthenticatedAppNewJobUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/compliance'
    | '/features'
    | '/how-it-works'
    | '/industries'
    | '/onboarding'
    | '/pricing'
    | '/sign-in'
    | '/sitemap.xml'
    | '/start'
    | '/templates'
    | '/app'
    | '/app/billing'
    | '/app/campaigns'
    | '/app/compliance'
    | '/app/dashboard'
    | '/app/lists'
    | '/app/new-job'
    | '/app/numbers'
    | '/app/settings'
    | '/app/'
    | '/app/campaigns/$campaignId'
    | '/app/jobs/$jobId'
    | '/app/new-job/business'
    | '/app/new-job/records'
    | '/app/new-job/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/compliance'
    | '/features'
    | '/how-it-works'
    | '/industries'
    | '/onboarding'
    | '/pricing'
    | '/sign-in'
    | '/sitemap.xml'
    | '/start'
    | '/templates'
    | '/app/billing'
    | '/app/campaigns'
    | '/app/compliance'
    | '/app/dashboard'
    | '/app/lists'
    | '/app/new-job'
    | '/app/numbers'
    | '/app/settings'
    | '/app'
    | '/app/campaigns/$campaignId'
    | '/app/jobs/$jobId'
    | '/app/new-job/business'
    | '/app/new-job/records'
    | '/app/new-job/upload'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/compliance'
    | '/features'
    | '/how-it-works'
    | '/industries'
    | '/onboarding'
    | '/pricing'
    | '/sign-in'
    | '/sitemap.xml'
    | '/start'
    | '/templates'
    | '/_authenticated/app'
    | '/_authenticated/app/billing'
    | '/_authenticated/app/campaigns'
    | '/_authenticated/app/compliance'
    | '/_authenticated/app/dashboard'
    | '/_authenticated/app/lists'
    | '/_authenticated/app/new-job'
    | '/_authenticated/app/numbers'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/'
    | '/_authenticated/app/campaigns/$campaignId'
    | '/_authenticated/app/jobs/$jobId'
    | '/_authenticated/app/new-job/business'
    | '/_authenticated/app/new-job/records'
    | '/_authenticated/app/new-job/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ComplianceRoute: typeof ComplianceRoute
  FeaturesRoute: typeof FeaturesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  IndustriesRoute: typeof IndustriesRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  SignInRoute: typeof SignInRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StartRoute: typeof StartRoute
  TemplatesRoute: typeof TemplatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/numbers': {
      id: '/_authenticated/app/numbers'
      path: '/numbers'
      fullPath: '/app/numbers'
      preLoaderRoute: typeof AuthenticatedAppNumbersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/new-job': {
      id: '/_authenticated/app/new-job'
      path: '/new-job'
      fullPath: '/app/new-job'
      preLoaderRoute: typeof AuthenticatedAppNewJobRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/lists': {
      id: '/_authenticated/app/lists'
      path: '/lists'
      fullPath: '/app/lists'
      preLoaderRoute: typeof AuthenticatedAppListsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/dashboard': {
      id: '/_authenticated/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/compliance': {
      id: '/_authenticated/app/compliance'
      path: '/compliance'
      fullPath: '/app/compliance'
      preLoaderRoute: typeof AuthenticatedAppComplianceRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/campaigns': {
      id: '/_authenticated/app/campaigns'
      path: '/campaigns'
      fullPath: '/app/campaigns'
      preLoaderRoute: typeof AuthenticatedAppCampaignsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/billing': {
      id: '/_authenticated/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AuthenticatedAppBillingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/new-job/upload': {
      id: '/_authenticated/app/new-job/upload'
      path: '/upload'
      fullPath: '/app/new-job/upload'
      preLoaderRoute: typeof AuthenticatedAppNewJobUploadRouteImport
      parentRoute: typeof AuthenticatedAppNewJobRoute
    }
    '/_authenticated/app/new-job/records': {
      id: '/_authenticated/app/new-job/records'
      path: '/records'
      fullPath: '/app/new-job/records'
      preLoaderRoute: typeof AuthenticatedAppNewJobRecordsRouteImport
      parentRoute: typeof AuthenticatedAppNewJobRoute
    }
    '/_authenticated/app/new-job/business': {
      id: '/_authenticated/app/new-job/business'
      path: '/business'
      fullPath: '/app/new-job/business'
      preLoaderRoute: typeof AuthenticatedAppNewJobBusinessRouteImport
      parentRoute: typeof AuthenticatedAppNewJobRoute
    }
    '/_authenticated/app/jobs/$jobId': {
      id: '/_authenticated/app/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/app/jobs/$jobId'
      preLoaderRoute: typeof AuthenticatedAppJobsJobIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/campaigns/$campaignId': {
      id: '/_authenticated/app/campaigns/$campaignId'
      path: '/$campaignId'
      fullPath: '/app/campaigns/$campaignId'
      preLoaderRoute: typeof AuthenticatedAppCampaignsCampaignIdRouteImport
      parentRoute: typeof AuthenticatedAppCampaignsRoute
    }
  }
}

interface AuthenticatedAppCampaignsRouteChildren {
  AuthenticatedAppCampaignsCampaignIdRoute: typeof AuthenticatedAppCampaignsCampaignIdRoute
}

const AuthenticatedAppCampaignsRouteChildren: AuthenticatedAppCampaignsRouteChildren =
  {
    AuthenticatedAppCampaignsCampaignIdRoute:
      AuthenticatedAppCampaignsCampaignIdRoute,
  }

const AuthenticatedAppCampaignsRouteWithChildren =
  AuthenticatedAppCampaignsRoute._addFileChildren(
    AuthenticatedAppCampaignsRouteChildren,
  )

interface AuthenticatedAppNewJobRouteChildren {
  AuthenticatedAppNewJobBusinessRoute: typeof AuthenticatedAppNewJobBusinessRoute
  AuthenticatedAppNewJobRecordsRoute: typeof AuthenticatedAppNewJobRecordsRoute
  AuthenticatedAppNewJobUploadRoute: typeof AuthenticatedAppNewJobUploadRoute
}

const AuthenticatedAppNewJobRouteChildren: AuthenticatedAppNewJobRouteChildren =
  {
    AuthenticatedAppNewJobBusinessRoute: AuthenticatedAppNewJobBusinessRoute,
    AuthenticatedAppNewJobRecordsRoute: AuthenticatedAppNewJobRecordsRoute,
    AuthenticatedAppNewJobUploadRoute: AuthenticatedAppNewJobUploadRoute,
  }

const AuthenticatedAppNewJobRouteWithChildren =
  AuthenticatedAppNewJobRoute._addFileChildren(
    AuthenticatedAppNewJobRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppBillingRoute: typeof AuthenticatedAppBillingRoute
  AuthenticatedAppCampaignsRoute: typeof AuthenticatedAppCampaignsRouteWithChildren
  AuthenticatedAppComplianceRoute: typeof AuthenticatedAppComplianceRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppListsRoute: typeof AuthenticatedAppListsRoute
  AuthenticatedAppNewJobRoute: typeof AuthenticatedAppNewJobRouteWithChildren
  AuthenticatedAppNumbersRoute: typeof AuthenticatedAppNumbersRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppJobsJobIdRoute: typeof AuthenticatedAppJobsJobIdRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppBillingRoute: AuthenticatedAppBillingRoute,
  AuthenticatedAppCampaignsRoute: AuthenticatedAppCampaignsRouteWithChildren,
  AuthenticatedAppComplianceRoute: AuthenticatedAppComplianceRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppListsRoute: AuthenticatedAppListsRoute,
  AuthenticatedAppNewJobRoute: AuthenticatedAppNewJobRouteWithChildren,
  AuthenticatedAppNumbersRoute: AuthenticatedAppNumbersRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppJobsJobIdRoute: AuthenticatedAppJobsJobIdRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ComplianceRoute: ComplianceRoute,
  FeaturesRoute: FeaturesRoute,
  HowItWorksRoute: HowItWorksRoute,
  IndustriesRoute: IndustriesRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  SignInRoute: SignInRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StartRoute: StartRoute,
  TemplatesRoute: TemplatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
