/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as StartRouteImport } from './routes/start'
import { Route as SolarRouteImport } from './routes/solar'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as RealestateRouteImport } from './routes/realestate'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MortgageRouteImport } from './routes/mortgage'
import { Route as MedicalRouteImport } from './routes/medical'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as HomeServicesRouteImport } from './routes/home-services'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as EducationRouteImport } from './routes/education'
import { Route as EcommerceRouteImport } from './routes/ecommerce'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as B2bRouteImport } from './routes/b2b'
import { Route as AutoRouteImport } from './routes/auto'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgencyRouteImport } from './routes/agency'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppTeamRouteImport } from './routes/_authenticated/app.team'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppReportsRouteImport } from './routes/_authenticated/app.reports'
import { Route as AuthenticatedAppRegistrationRouteImport } from './routes/_authenticated/app.registration'
import { Route as AuthenticatedAppNumbersRouteImport } from './routes/_authenticated/app.numbers'
import { Route as AuthenticatedAppNewJobRouteImport } from './routes/_authenticated/app.new-job'
import { Route as AuthenticatedAppListsRouteImport } from './routes/_authenticated/app.lists'
import { Route as AuthenticatedAppInboxRouteImport } from './routes/_authenticated/app.inbox'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/app.dashboard'
import { Route as AuthenticatedAppComplianceRouteImport } from './routes/_authenticated/app.compliance'
import { Route as AuthenticatedAppCampaignsRouteImport } from './routes/_authenticated/app.campaigns'
import { Route as AuthenticatedAppBillingRouteImport } from './routes/_authenticated/app.billing'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated/app.admin'
import { Route as AuthenticatedAppAccountRouteImport } from './routes/_authenticated/app.account'
import { Route as ApiPublicHooksTickCampaignsRouteImport } from './routes/api/public/hooks/tick-campaigns'
import { Route as ApiPublicHooksTelnyxInboundRouteImport } from './routes/api/public/hooks/telnyx-inbound'
import { Route as ApiPublicHooksTelnyxDlrRouteImport } from './routes/api/public/hooks/telnyx-dlr'
import { Route as ApiPublicHooksInboundSmsRouteImport } from './routes/api/public/hooks/inbound-sms'
import { Route as AuthenticatedAppNewJobUploadRouteImport } from './routes/_authenticated/app.new-job.upload'
import { Route as AuthenticatedAppNewJobRecordsRouteImport } from './routes/_authenticated/app.new-job.records'
import { Route as AuthenticatedAppNewJobBusinessRouteImport } from './routes/_authenticated/app.new-job.business'
import { Route as AuthenticatedAppJobsJobIdRouteImport } from './routes/_authenticated/app.jobs.$jobId'
import { Route as AuthenticatedAppCampaignsNewRouteImport } from './routes/_authenticated/app.campaigns.new'
import { Route as AuthenticatedAppCampaignsCampaignIdRouteImport } from './routes/_authenticated/app.campaigns.$campaignId'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const SolarRoute = SolarRouteImport.update({
  id: '/solar',
  path: '/solar',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const RealestateRoute = RealestateRouteImport.update({
  id: '/realestate',
  path: '/realestate',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MortgageRoute = MortgageRouteImport.update({
  id: '/mortgage',
  path: '/mortgage',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalRoute = MedicalRouteImport.update({
  id: '/medical',
  path: '/medical',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeServicesRoute = HomeServicesRouteImport.update({
  id: '/home-services',
  path: '/home-services',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const EcommerceRoute = EcommerceRouteImport.update({
  id: '/ecommerce',
  path: '/ecommerce',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const B2bRoute = B2bRouteImport.update({
  id: '/b2b',
  path: '/b2b',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoRoute = AutoRouteImport.update({
  id: '/auto',
  path: '/auto',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyRoute = AgencyRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTeamRoute = AuthenticatedAppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppReportsRoute = AuthenticatedAppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRegistrationRoute =
  AuthenticatedAppRegistrationRouteImport.update({
    id: '/registration',
    path: '/registration',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppNumbersRoute = AuthenticatedAppNumbersRouteImport.update({
  id: '/numbers',
  path: '/numbers',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppNewJobRoute = AuthenticatedAppNewJobRouteImport.update({
  id: '/new-job',
  path: '/new-job',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppListsRoute = AuthenticatedAppListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppInboxRoute = AuthenticatedAppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppComplianceRoute =
  AuthenticatedAppComplianceRouteImport.update({
    id: '/compliance',
    path: '/compliance',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCampaignsRoute =
  AuthenticatedAppCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBillingRoute = AuthenticatedAppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAccountRoute = AuthenticatedAppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ApiPublicHooksTickCampaignsRoute =
  ApiPublicHooksTickCampaignsRouteImport.update({
    id: '/api/public/hooks/tick-campaigns',
    path: '/api/public/hooks/tick-campaigns',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTelnyxInboundRoute =
  ApiPublicHooksTelnyxInboundRouteImport.update({
    id: '/api/public/hooks/telnyx-inbound',
    path: '/api/public/hooks/telnyx-inbound',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTelnyxDlrRoute = ApiPublicHooksTelnyxDlrRouteImport.update({
  id: '/api/public/hooks/telnyx-dlr',
  path: '/api/public/hooks/telnyx-dlr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksInboundSmsRoute =
  ApiPublicHooksInboundSmsRouteImport.update({
    id: '/api/public/hooks/inbound-sms',
    path: '/api/public/hooks/inbound-sms',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppNewJobUploadRoute =
  AuthenticatedAppNewJobUploadRouteImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => AuthenticatedAppNewJobRoute,
  } as any)
const AuthenticatedAppNewJobRecordsRoute =
  AuthenticatedAppNewJobRecordsRouteImport.update({
    id: '/records',
    path: '/records',
    getParentRoute: () => AuthenticatedAppNewJobRoute,
  } as any)
const AuthenticatedAppNewJobBusinessRoute =
  AuthenticatedAppNewJobBusinessRouteImport.update({
    id: '/business',
    path: '/business',
    getParentRoute: () => AuthenticatedAppNewJobRoute,
  } as any)
const AuthenticatedAppJobsJobIdRoute =
  AuthenticatedAppJobsJobIdRouteImport.update({
    id: '/jobs/$jobId',
    path: '/jobs/$jobId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCampaignsNewRoute =
  AuthenticatedAppCampaignsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAppCampaignsRoute,
  } as any)
const AuthenticatedAppCampaignsCampaignIdRoute =
  AuthenticatedAppCampaignsCampaignIdRouteImport.update({
    id: '/$campaignId',
    path: '/$campaignId',
    getParentRoute: () => AuthenticatedAppCampaignsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/agency': typeof AgencyRoute
  '/auth': typeof AuthRoute
  '/auto': typeof AutoRoute
  '/b2b': typeof B2bRoute
  '/compliance': typeof ComplianceRoute
  '/ecommerce': typeof EcommerceRoute
  '/education': typeof EducationRoute
  '/features': typeof FeaturesRoute
  '/home-services': typeof HomeServicesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/industries': typeof IndustriesRoute
  '/insurance': typeof InsuranceRoute
  '/legal': typeof LegalRoute
  '/medical': typeof MedicalRoute
  '/mortgage': typeof MortgageRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/realestate': typeof RealestateRoute
  '/sign-in': typeof SignInRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solar': typeof SolarRoute
  '/start': typeof StartRoute
  '/templates': typeof TemplatesRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/account': typeof AuthenticatedAppAccountRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/campaigns': typeof AuthenticatedAppCampaignsRouteWithChildren
  '/app/compliance': typeof AuthenticatedAppComplianceRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/inbox': typeof AuthenticatedAppInboxRoute
  '/app/lists': typeof AuthenticatedAppListsRoute
  '/app/new-job': typeof AuthenticatedAppNewJobRouteWithChildren
  '/app/numbers': typeof AuthenticatedAppNumbersRoute
  '/app/registration': typeof AuthenticatedAppRegistrationRoute
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/campaigns/$campaignId': typeof AuthenticatedAppCampaignsCampaignIdRoute
  '/app/campaigns/new': typeof AuthenticatedAppCampaignsNewRoute
  '/app/jobs/$jobId': typeof AuthenticatedAppJobsJobIdRoute
  '/app/new-job/business': typeof AuthenticatedAppNewJobBusinessRoute
  '/app/new-job/records': typeof AuthenticatedAppNewJobRecordsRoute
  '/app/new-job/upload': typeof AuthenticatedAppNewJobUploadRoute
  '/api/public/hooks/inbound-sms': typeof ApiPublicHooksInboundSmsRoute
  '/api/public/hooks/telnyx-dlr': typeof ApiPublicHooksTelnyxDlrRoute
  '/api/public/hooks/telnyx-inbound': typeof ApiPublicHooksTelnyxInboundRoute
  '/api/public/hooks/tick-campaigns': typeof ApiPublicHooksTickCampaignsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/agency': typeof AgencyRoute
  '/auth': typeof AuthRoute
  '/auto': typeof AutoRoute
  '/b2b': typeof B2bRoute
  '/compliance': typeof ComplianceRoute
  '/ecommerce': typeof EcommerceRoute
  '/education': typeof EducationRoute
  '/features': typeof FeaturesRoute
  '/home-services': typeof HomeServicesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/industries': typeof IndustriesRoute
  '/insurance': typeof InsuranceRoute
  '/legal': typeof LegalRoute
  '/medical': typeof MedicalRoute
  '/mortgage': typeof MortgageRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/realestate': typeof RealestateRoute
  '/sign-in': typeof SignInRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solar': typeof SolarRoute
  '/start': typeof StartRoute
  '/templates': typeof TemplatesRoute
  '/app/account': typeof AuthenticatedAppAccountRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/campaigns': typeof AuthenticatedAppCampaignsRouteWithChildren
  '/app/compliance': typeof AuthenticatedAppComplianceRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/inbox': typeof AuthenticatedAppInboxRoute
  '/app/lists': typeof AuthenticatedAppListsRoute
  '/app/new-job': typeof AuthenticatedAppNewJobRouteWithChildren
  '/app/numbers': typeof AuthenticatedAppNumbersRoute
  '/app/registration': typeof AuthenticatedAppRegistrationRoute
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/campaigns/$campaignId': typeof AuthenticatedAppCampaignsCampaignIdRoute
  '/app/campaigns/new': typeof AuthenticatedAppCampaignsNewRoute
  '/app/jobs/$jobId': typeof AuthenticatedAppJobsJobIdRoute
  '/app/new-job/business': typeof AuthenticatedAppNewJobBusinessRoute
  '/app/new-job/records': typeof AuthenticatedAppNewJobRecordsRoute
  '/app/new-job/upload': typeof AuthenticatedAppNewJobUploadRoute
  '/api/public/hooks/inbound-sms': typeof ApiPublicHooksInboundSmsRoute
  '/api/public/hooks/telnyx-dlr': typeof ApiPublicHooksTelnyxDlrRoute
  '/api/public/hooks/telnyx-inbound': typeof ApiPublicHooksTelnyxInboundRoute
  '/api/public/hooks/tick-campaigns': typeof ApiPublicHooksTickCampaignsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/agency': typeof AgencyRoute
  '/auth': typeof AuthRoute
  '/auto': typeof AutoRoute
  '/b2b': typeof B2bRoute
  '/compliance': typeof ComplianceRoute
  '/ecommerce': typeof EcommerceRoute
  '/education': typeof EducationRoute
  '/features': typeof FeaturesRoute
  '/home-services': typeof HomeServicesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/industries': typeof IndustriesRoute
  '/insurance': typeof InsuranceRoute
  '/legal': typeof LegalRoute
  '/medical': typeof MedicalRoute
  '/mortgage': typeof MortgageRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/realestate': typeof RealestateRoute
  '/sign-in': typeof SignInRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solar': typeof SolarRoute
  '/start': typeof StartRoute
  '/templates': typeof TemplatesRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/account': typeof AuthenticatedAppAccountRoute
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRoute
  '/_authenticated/app/billing': typeof AuthenticatedAppBillingRoute
  '/_authenticated/app/campaigns': typeof AuthenticatedAppCampaignsRouteWithChildren
  '/_authenticated/app/compliance': typeof AuthenticatedAppComplianceRoute
  '/_authenticated/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/app/inbox': typeof AuthenticatedAppInboxRoute
  '/_authenticated/app/lists': typeof AuthenticatedAppListsRoute
  '/_authenticated/app/new-job': typeof AuthenticatedAppNewJobRouteWithChildren
  '/_authenticated/app/numbers': typeof AuthenticatedAppNumbersRoute
  '/_authenticated/app/registration': typeof AuthenticatedAppRegistrationRoute
  '/_authenticated/app/reports': typeof AuthenticatedAppReportsRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/team': typeof AuthenticatedAppTeamRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/campaigns/$campaignId': typeof AuthenticatedAppCampaignsCampaignIdRoute
  '/_authenticated/app/campaigns/new': typeof AuthenticatedAppCampaignsNewRoute
  '/_authenticated/app/jobs/$jobId': typeof AuthenticatedAppJobsJobIdRoute
  '/_authenticated/app/new-job/business': typeof AuthenticatedAppNewJobBusinessRoute
  '/_authenticated/app/new-job/records': typeof AuthenticatedAppNewJobRecordsRoute
  '/_authenticated/app/new-job/upload': typeof AuthenticatedAppNewJobUploadRoute
  '/api/public/hooks/inbound-sms': typeof ApiPublicHooksInboundSmsRoute
  '/api/public/hooks/telnyx-dlr': typeof ApiPublicHooksTelnyxDlrRoute
  '/api/public/hooks/telnyx-inbound': typeof ApiPublicHooksTelnyxInboundRoute
  '/api/public/hooks/tick-campaigns': typeof ApiPublicHooksTickCampaignsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/agency'
    | '/auth'
    | '/auto'
    | '/b2b'
    | '/compliance'
    | '/ecommerce'
    | '/education'
    | '/features'
    | '/home-services'
    | '/how-it-works'
    | '/industries'
    | '/insurance'
    | '/legal'
    | '/medical'
    | '/mortgage'
    | '/onboarding'
    | '/pricing'
    | '/realestate'
    | '/sign-in'
    | '/sitemap.xml'
    | '/solar'
    | '/start'
    | '/templates'
    | '/app'
    | '/app/account'
    | '/app/admin'
    | '/app/billing'
    | '/app/campaigns'
    | '/app/compliance'
    | '/app/dashboard'
    | '/app/inbox'
    | '/app/lists'
    | '/app/new-job'
    | '/app/numbers'
    | '/app/registration'
    | '/app/reports'
    | '/app/settings'
    | '/app/team'
    | '/app/'
    | '/app/campaigns/$campaignId'
    | '/app/campaigns/new'
    | '/app/jobs/$jobId'
    | '/app/new-job/business'
    | '/app/new-job/records'
    | '/app/new-job/upload'
    | '/api/public/hooks/inbound-sms'
    | '/api/public/hooks/telnyx-dlr'
    | '/api/public/hooks/telnyx-inbound'
    | '/api/public/hooks/tick-campaigns'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/agency'
    | '/auth'
    | '/auto'
    | '/b2b'
    | '/compliance'
    | '/ecommerce'
    | '/education'
    | '/features'
    | '/home-services'
    | '/how-it-works'
    | '/industries'
    | '/insurance'
    | '/legal'
    | '/medical'
    | '/mortgage'
    | '/onboarding'
    | '/pricing'
    | '/realestate'
    | '/sign-in'
    | '/sitemap.xml'
    | '/solar'
    | '/start'
    | '/templates'
    | '/app/account'
    | '/app/admin'
    | '/app/billing'
    | '/app/campaigns'
    | '/app/compliance'
    | '/app/dashboard'
    | '/app/inbox'
    | '/app/lists'
    | '/app/new-job'
    | '/app/numbers'
    | '/app/registration'
    | '/app/reports'
    | '/app/settings'
    | '/app/team'
    | '/app'
    | '/app/campaigns/$campaignId'
    | '/app/campaigns/new'
    | '/app/jobs/$jobId'
    | '/app/new-job/business'
    | '/app/new-job/records'
    | '/app/new-job/upload'
    | '/api/public/hooks/inbound-sms'
    | '/api/public/hooks/telnyx-dlr'
    | '/api/public/hooks/telnyx-inbound'
    | '/api/public/hooks/tick-campaigns'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accept-invite'
    | '/agency'
    | '/auth'
    | '/auto'
    | '/b2b'
    | '/compliance'
    | '/ecommerce'
    | '/education'
    | '/features'
    | '/home-services'
    | '/how-it-works'
    | '/industries'
    | '/insurance'
    | '/legal'
    | '/medical'
    | '/mortgage'
    | '/onboarding'
    | '/pricing'
    | '/realestate'
    | '/sign-in'
    | '/sitemap.xml'
    | '/solar'
    | '/start'
    | '/templates'
    | '/_authenticated/app'
    | '/_authenticated/app/account'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/billing'
    | '/_authenticated/app/campaigns'
    | '/_authenticated/app/compliance'
    | '/_authenticated/app/dashboard'
    | '/_authenticated/app/inbox'
    | '/_authenticated/app/lists'
    | '/_authenticated/app/new-job'
    | '/_authenticated/app/numbers'
    | '/_authenticated/app/registration'
    | '/_authenticated/app/reports'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/team'
    | '/_authenticated/app/'
    | '/_authenticated/app/campaigns/$campaignId'
    | '/_authenticated/app/campaigns/new'
    | '/_authenticated/app/jobs/$jobId'
    | '/_authenticated/app/new-job/business'
    | '/_authenticated/app/new-job/records'
    | '/_authenticated/app/new-job/upload'
    | '/api/public/hooks/inbound-sms'
    | '/api/public/hooks/telnyx-dlr'
    | '/api/public/hooks/telnyx-inbound'
    | '/api/public/hooks/tick-campaigns'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  AgencyRoute: typeof AgencyRoute
  AuthRoute: typeof AuthRoute
  AutoRoute: typeof AutoRoute
  B2bRoute: typeof B2bRoute
  ComplianceRoute: typeof ComplianceRoute
  EcommerceRoute: typeof EcommerceRoute
  EducationRoute: typeof EducationRoute
  FeaturesRoute: typeof FeaturesRoute
  HomeServicesRoute: typeof HomeServicesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  IndustriesRoute: typeof IndustriesRoute
  InsuranceRoute: typeof InsuranceRoute
  LegalRoute: typeof LegalRoute
  MedicalRoute: typeof MedicalRoute
  MortgageRoute: typeof MortgageRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  RealestateRoute: typeof RealestateRoute
  SignInRoute: typeof SignInRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolarRoute: typeof SolarRoute
  StartRoute: typeof StartRoute
  TemplatesRoute: typeof TemplatesRoute
  ApiPublicHooksInboundSmsRoute: typeof ApiPublicHooksInboundSmsRoute
  ApiPublicHooksTelnyxDlrRoute: typeof ApiPublicHooksTelnyxDlrRoute
  ApiPublicHooksTelnyxInboundRoute: typeof ApiPublicHooksTelnyxInboundRoute
  ApiPublicHooksTickCampaignsRoute: typeof ApiPublicHooksTickCampaignsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solar': {
      id: '/solar'
      path: '/solar'
      fullPath: '/solar'
      preLoaderRoute: typeof SolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realestate': {
      id: '/realestate'
      path: '/realestate'
      fullPath: '/realestate'
      preLoaderRoute: typeof RealestateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mortgage': {
      id: '/mortgage'
      path: '/mortgage'
      fullPath: '/mortgage'
      preLoaderRoute: typeof MortgageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical': {
      id: '/medical'
      path: '/medical'
      fullPath: '/medical'
      preLoaderRoute: typeof MedicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-services': {
      id: '/home-services'
      path: '/home-services'
      fullPath: '/home-services'
      preLoaderRoute: typeof HomeServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecommerce': {
      id: '/ecommerce'
      path: '/ecommerce'
      fullPath: '/ecommerce'
      preLoaderRoute: typeof EcommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b2b': {
      id: '/b2b'
      path: '/b2b'
      fullPath: '/b2b'
      preLoaderRoute: typeof B2bRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto': {
      id: '/auto'
      path: '/auto'
      fullPath: '/auto'
      preLoaderRoute: typeof AutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency': {
      id: '/agency'
      path: '/agency'
      fullPath: '/agency'
      preLoaderRoute: typeof AgencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/team': {
      id: '/_authenticated/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AuthenticatedAppTeamRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/reports': {
      id: '/_authenticated/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AuthenticatedAppReportsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/registration': {
      id: '/_authenticated/app/registration'
      path: '/registration'
      fullPath: '/app/registration'
      preLoaderRoute: typeof AuthenticatedAppRegistrationRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/numbers': {
      id: '/_authenticated/app/numbers'
      path: '/numbers'
      fullPath: '/app/numbers'
      preLoaderRoute: typeof AuthenticatedAppNumbersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/new-job': {
      id: '/_authenticated/app/new-job'
      path: '/new-job'
      fullPath: '/app/new-job'
      preLoaderRoute: typeof AuthenticatedAppNewJobRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/lists': {
      id: '/_authenticated/app/lists'
      path: '/lists'
      fullPath: '/app/lists'
      preLoaderRoute: typeof AuthenticatedAppListsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/inbox': {
      id: '/_authenticated/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AuthenticatedAppInboxRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/dashboard': {
      id: '/_authenticated/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/compliance': {
      id: '/_authenticated/app/compliance'
      path: '/compliance'
      fullPath: '/app/compliance'
      preLoaderRoute: typeof AuthenticatedAppComplianceRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/campaigns': {
      id: '/_authenticated/app/campaigns'
      path: '/campaigns'
      fullPath: '/app/campaigns'
      preLoaderRoute: typeof AuthenticatedAppCampaignsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/billing': {
      id: '/_authenticated/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AuthenticatedAppBillingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/account': {
      id: '/_authenticated/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AuthenticatedAppAccountRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/hooks/tick-campaigns': {
      id: '/api/public/hooks/tick-campaigns'
      path: '/api/public/hooks/tick-campaigns'
      fullPath: '/api/public/hooks/tick-campaigns'
      preLoaderRoute: typeof ApiPublicHooksTickCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/telnyx-inbound': {
      id: '/api/public/hooks/telnyx-inbound'
      path: '/api/public/hooks/telnyx-inbound'
      fullPath: '/api/public/hooks/telnyx-inbound'
      preLoaderRoute: typeof ApiPublicHooksTelnyxInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/telnyx-dlr': {
      id: '/api/public/hooks/telnyx-dlr'
      path: '/api/public/hooks/telnyx-dlr'
      fullPath: '/api/public/hooks/telnyx-dlr'
      preLoaderRoute: typeof ApiPublicHooksTelnyxDlrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/inbound-sms': {
      id: '/api/public/hooks/inbound-sms'
      path: '/api/public/hooks/inbound-sms'
      fullPath: '/api/public/hooks/inbound-sms'
      preLoaderRoute: typeof ApiPublicHooksInboundSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/new-job/upload': {
      id: '/_authenticated/app/new-job/upload'
      path: '/upload'
      fullPath: '/app/new-job/upload'
      preLoaderRoute: typeof AuthenticatedAppNewJobUploadRouteImport
      parentRoute: typeof AuthenticatedAppNewJobRoute
    }
    '/_authenticated/app/new-job/records': {
      id: '/_authenticated/app/new-job/records'
      path: '/records'
      fullPath: '/app/new-job/records'
      preLoaderRoute: typeof AuthenticatedAppNewJobRecordsRouteImport
      parentRoute: typeof AuthenticatedAppNewJobRoute
    }
    '/_authenticated/app/new-job/business': {
      id: '/_authenticated/app/new-job/business'
      path: '/business'
      fullPath: '/app/new-job/business'
      preLoaderRoute: typeof AuthenticatedAppNewJobBusinessRouteImport
      parentRoute: typeof AuthenticatedAppNewJobRoute
    }
    '/_authenticated/app/jobs/$jobId': {
      id: '/_authenticated/app/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/app/jobs/$jobId'
      preLoaderRoute: typeof AuthenticatedAppJobsJobIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/campaigns/new': {
      id: '/_authenticated/app/campaigns/new'
      path: '/new'
      fullPath: '/app/campaigns/new'
      preLoaderRoute: typeof AuthenticatedAppCampaignsNewRouteImport
      parentRoute: typeof AuthenticatedAppCampaignsRoute
    }
    '/_authenticated/app/campaigns/$campaignId': {
      id: '/_authenticated/app/campaigns/$campaignId'
      path: '/$campaignId'
      fullPath: '/app/campaigns/$campaignId'
      preLoaderRoute: typeof AuthenticatedAppCampaignsCampaignIdRouteImport
      parentRoute: typeof AuthenticatedAppCampaignsRoute
    }
  }
}

interface AuthenticatedAppCampaignsRouteChildren {
  AuthenticatedAppCampaignsCampaignIdRoute: typeof AuthenticatedAppCampaignsCampaignIdRoute
  AuthenticatedAppCampaignsNewRoute: typeof AuthenticatedAppCampaignsNewRoute
}

const AuthenticatedAppCampaignsRouteChildren: AuthenticatedAppCampaignsRouteChildren =
  {
    AuthenticatedAppCampaignsCampaignIdRoute:
      AuthenticatedAppCampaignsCampaignIdRoute,
    AuthenticatedAppCampaignsNewRoute: AuthenticatedAppCampaignsNewRoute,
  }

const AuthenticatedAppCampaignsRouteWithChildren =
  AuthenticatedAppCampaignsRoute._addFileChildren(
    AuthenticatedAppCampaignsRouteChildren,
  )

interface AuthenticatedAppNewJobRouteChildren {
  AuthenticatedAppNewJobBusinessRoute: typeof AuthenticatedAppNewJobBusinessRoute
  AuthenticatedAppNewJobRecordsRoute: typeof AuthenticatedAppNewJobRecordsRoute
  AuthenticatedAppNewJobUploadRoute: typeof AuthenticatedAppNewJobUploadRoute
}

const AuthenticatedAppNewJobRouteChildren: AuthenticatedAppNewJobRouteChildren =
  {
    AuthenticatedAppNewJobBusinessRoute: AuthenticatedAppNewJobBusinessRoute,
    AuthenticatedAppNewJobRecordsRoute: AuthenticatedAppNewJobRecordsRoute,
    AuthenticatedAppNewJobUploadRoute: AuthenticatedAppNewJobUploadRoute,
  }

const AuthenticatedAppNewJobRouteWithChildren =
  AuthenticatedAppNewJobRoute._addFileChildren(
    AuthenticatedAppNewJobRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAccountRoute: typeof AuthenticatedAppAccountRoute
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRoute
  AuthenticatedAppBillingRoute: typeof AuthenticatedAppBillingRoute
  AuthenticatedAppCampaignsRoute: typeof AuthenticatedAppCampaignsRouteWithChildren
  AuthenticatedAppComplianceRoute: typeof AuthenticatedAppComplianceRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppInboxRoute: typeof AuthenticatedAppInboxRoute
  AuthenticatedAppListsRoute: typeof AuthenticatedAppListsRoute
  AuthenticatedAppNewJobRoute: typeof AuthenticatedAppNewJobRouteWithChildren
  AuthenticatedAppNumbersRoute: typeof AuthenticatedAppNumbersRoute
  AuthenticatedAppRegistrationRoute: typeof AuthenticatedAppRegistrationRoute
  AuthenticatedAppReportsRoute: typeof AuthenticatedAppReportsRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppTeamRoute: typeof AuthenticatedAppTeamRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppJobsJobIdRoute: typeof AuthenticatedAppJobsJobIdRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAccountRoute: AuthenticatedAppAccountRoute,
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRoute,
  AuthenticatedAppBillingRoute: AuthenticatedAppBillingRoute,
  AuthenticatedAppCampaignsRoute: AuthenticatedAppCampaignsRouteWithChildren,
  AuthenticatedAppComplianceRoute: AuthenticatedAppComplianceRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppInboxRoute: AuthenticatedAppInboxRoute,
  AuthenticatedAppListsRoute: AuthenticatedAppListsRoute,
  AuthenticatedAppNewJobRoute: AuthenticatedAppNewJobRouteWithChildren,
  AuthenticatedAppNumbersRoute: AuthenticatedAppNumbersRoute,
  AuthenticatedAppRegistrationRoute: AuthenticatedAppRegistrationRoute,
  AuthenticatedAppReportsRoute: AuthenticatedAppReportsRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppTeamRoute: AuthenticatedAppTeamRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppJobsJobIdRoute: AuthenticatedAppJobsJobIdRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  AgencyRoute: AgencyRoute,
  AuthRoute: AuthRoute,
  AutoRoute: AutoRoute,
  B2bRoute: B2bRoute,
  ComplianceRoute: ComplianceRoute,
  EcommerceRoute: EcommerceRoute,
  EducationRoute: EducationRoute,
  FeaturesRoute: FeaturesRoute,
  HomeServicesRoute: HomeServicesRoute,
  HowItWorksRoute: HowItWorksRoute,
  IndustriesRoute: IndustriesRoute,
  InsuranceRoute: InsuranceRoute,
  LegalRoute: LegalRoute,
  MedicalRoute: MedicalRoute,
  MortgageRoute: MortgageRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  RealestateRoute: RealestateRoute,
  SignInRoute: SignInRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolarRoute: SolarRoute,
  StartRoute: StartRoute,
  TemplatesRoute: TemplatesRoute,
  ApiPublicHooksInboundSmsRoute: ApiPublicHooksInboundSmsRoute,
  ApiPublicHooksTelnyxDlrRoute: ApiPublicHooksTelnyxDlrRoute,
  ApiPublicHooksTelnyxInboundRoute: ApiPublicHooksTelnyxInboundRoute,
  ApiPublicHooksTickCampaignsRoute: ApiPublicHooksTickCampaignsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
